# Generated by Django 3.1 on 2020-09-01 02:14

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionTypeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='contribution id')),
                ('name', models.CharField(max_length=120, verbose_name='contribution name')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2020, 9, 1, 2, 14, 9, 281374, tzinfo=utc), verbose_name='add time')),
            ],
            options={
                'verbose_name': 'contribution',
                'verbose_name_plural': 'contribution',
            },
        ),
        migrations.CreateModel(
            name='ManuscriptModel',
            fields=[
                ('manuscript_id', models.CharField(max_length=18, primary_key=True, serialize=False, verbose_name='manuscript id')),
                ('title', models.CharField(max_length=256, verbose_name='manuscript title')),
                ('author', models.CharField(max_length=128, verbose_name='author name')),
                ('abstract', models.TextField(verbose_name='abstract')),
                ('textOfManuscript', models.TextField(verbose_name='text of manuscript')),
                ('reference', models.TextField(verbose_name='reference')),
                ('corresponding_author', models.CharField(max_length=150, verbose_name='corresponding author')),
                ('corresponding_author_contact_way', models.CharField(max_length=64, verbose_name='contact information of corresponding author')),
                ('memory_way', models.CharField(max_length=256, verbose_name='memory way')),
                ('contribution_time', models.DateTimeField(default=datetime.datetime(2020, 9, 1, 2, 14, 9, 282373, tzinfo=utc), verbose_name='delivery time')),
                ('contribution_type', models.ManyToManyField(to='manuscript.ContributionTypeModel', verbose_name='contribution type')),
            ],
            options={
                'verbose_name': 'manuscript',
                'verbose_name_plural': 'manuscript',
                'permissions': (('change_oneself_manuscript', 'Can change oneself manuscript'), ('delete_oneself_manuscript', 'Can delete oneself manuscript'), ('view_onesef_manuscript', 'Can view oneself manuscript')),
            },
        ),
        migrations.CreateModel(
            name='SubjectModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='subject id')),
                ('name', models.CharField(max_length=150, verbose_name='subject name')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2020, 9, 1, 2, 14, 9, 280372, tzinfo=utc), verbose_name='add time')),
            ],
            options={
                'verbose_name': 'subject',
                'verbose_name_plural': 'subject',
            },
        ),
        migrations.CreateModel(
            name='TradeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='trade')),
                ('name', models.CharField(max_length=120, verbose_name='trade name')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2020, 9, 1, 2, 14, 9, 281374, tzinfo=utc), verbose_name='add time')),
            ],
            options={
                'verbose_name': 'trade',
                'verbose_name_plural': 'trade',
            },
        ),
        migrations.CreateModel(
            name='ReviewManuscriptModel',
            fields=[
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False, verbose_name='review id')),
                ('preliminary_status', models.CharField(blank=True, max_length=16, null=True, verbose_name='preliminary status')),
                ('preliminary_evaluation', models.TextField(blank=True, null=True, verbose_name='preliminary evaluation')),
                ('preliminary_user', models.CharField(blank=True, max_length=150, null=True, verbose_name='preliminary user')),
                ('preliminary_user_contact_way', models.CharField(blank=True, max_length=64, null=True, verbose_name='preliminary user contact way')),
                ('preliminary_time', models.DateTimeField(blank=True, null=True, verbose_name='preliminary time')),
                ('preliminary_deadline', models.DateTimeField(blank=True, null=True, verbose_name='preliminary deadline')),
                ('external_audit_evaluation', models.TextField(blank=True, null=True, verbose_name='external audit evaluation')),
                ('external_audit_user', models.CharField(blank=True, max_length=150, null=True, verbose_name='external audit user')),
                ('external_audit_user_contact_way', models.CharField(blank=True, max_length=64, null=True, verbose_name='external audit user contact way')),
                ('external_audit_time', models.DateTimeField(blank=True, null=True, verbose_name='external audit time')),
                ('external_audit_deadline', models.DateTimeField(blank=True, null=True, verbose_name='external audit deadline')),
                ('review_status', models.CharField(blank=True, max_length=16, null=True, verbose_name='review status')),
                ('review_evaluation', models.TextField(blank=True, null=True, verbose_name='review evaluation')),
                ('review_user', models.CharField(blank=True, max_length=150, null=True, verbose_name='review user')),
                ('review_user_contact_way', models.CharField(blank=True, max_length=64, null=True, verbose_name='review user contact way')),
                ('review_time', models.DateTimeField(blank=True, null=True, verbose_name='review time')),
                ('review_deadline', models.DateTimeField(blank=True, null=True, verbose_name='review deadline')),
                ('final_judgment_status', models.CharField(blank=True, max_length=16, null=True, verbose_name='final judgment status')),
                ('final_judgment_evaluation', models.TextField(blank=True, null=True, verbose_name='final judgment evaluation')),
                ('final_judgment_user', models.CharField(blank=True, max_length=150, null=True, verbose_name='final judgment user')),
                ('final_judgment_user_contact_way', models.CharField(blank=True, max_length=64, null=True, verbose_name='final judgment user contact way')),
                ('final_judgment_time', models.DateTimeField(blank=True, null=True, verbose_name='final judgment time')),
                ('final_judgment_deadline', models.DateTimeField(blank=True, null=True, verbose_name='final judgment deadline')),
                ('manuscript', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manuscript.manuscriptmodel', verbose_name='manuscript')),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'review',
            },
        ),
        migrations.AddField(
            model_name='manuscriptmodel',
            name='subject',
            field=models.ManyToManyField(to='manuscript.SubjectModel', verbose_name='subject'),
        ),
        migrations.AddField(
            model_name='manuscriptmodel',
            name='trade',
            field=models.ManyToManyField(to='manuscript.TradeModel', verbose_name='trade'),
        ),
        migrations.CreateModel(
            name='CheckManuscriptModel',
            fields=[
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False, verbose_name='check id')),
                ('check_name', models.CharField(max_length=150, verbose_name='check name')),
                ('check_contact_way', models.CharField(max_length=64, verbose_name='contact way')),
                ('duplicate_checking_rate', models.FloatField(verbose_name='duplicate checking rate')),
                ('multiple_contributions_to_one_manuscript', models.BooleanField(verbose_name='multiple contributions to one manuscript')),
                ('is_subject', models.BooleanField(verbose_name='subject')),
                ('is_contribution', models.BooleanField(verbose_name='contribution')),
                ('is_trade', models.BooleanField(verbose_name='trade')),
                ('check_status', models.CharField(max_length=16, verbose_name='check status')),
                ('check_time', models.DateTimeField(default=datetime.datetime(2020, 9, 1, 2, 14, 9, 284372, tzinfo=utc), verbose_name='check time')),
                ('manuscript', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manuscript.manuscriptmodel', verbose_name='manuscript')),
            ],
            options={
                'verbose_name': 'check',
                'verbose_name_plural': 'check',
            },
        ),
    ]
