# Generated by Django 3.1 on 2020-09-01 17:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manuscriptmodel',
            options={'permissions': (('change_oneself_manuscript', 'Can change oneself manuscript'), ('delete_oneself_manuscript', 'Can delete oneself manuscript'), ('view_oneself_manuscript', 'Can view oneself manuscript')), 'verbose_name': 'manuscript', 'verbose_name_plural': 'manuscript'},
        ),
        migrations.RemoveField(
            model_name='checkmanuscriptmodel',
            name='manuscript',
        ),
        migrations.RemoveField(
            model_name='reviewmanuscriptmodel',
            name='manuscript',
        ),
        migrations.AddField(
            model_name='manuscriptmodel',
            name='check_status',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.checkmanuscriptmodel', verbose_name='manuscript inspection'),
        ),
        migrations.AddField(
            model_name='manuscriptmodel',
            name='review_status',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.reviewmanuscriptmodel', verbose_name='manuscript review'),
        ),
        migrations.AlterField(
            model_name='checkmanuscriptmodel',
            name='check_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 1, 17, 57, 23, 12461, tzinfo=utc), verbose_name='check time'),
        ),
        migrations.AlterField(
            model_name='contributiontypemodel',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 1, 17, 57, 23, 11463, tzinfo=utc), verbose_name='add time'),
        ),
        migrations.AlterField(
            model_name='manuscriptmodel',
            name='contribution_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 1, 17, 57, 23, 13460, tzinfo=utc), verbose_name='delivery time'),
        ),
        migrations.AlterField(
            model_name='manuscriptmodel',
            name='memory_way',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='memory way'),
        ),
        migrations.AlterField(
            model_name='subjectmodel',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 1, 17, 57, 23, 10462, tzinfo=utc), verbose_name='add time'),
        ),
        migrations.AlterField(
            model_name='trademodel',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 1, 17, 57, 23, 11463, tzinfo=utc), verbose_name='add time'),
        ),
    ]
