# Generated by Django 3.1 on 2020-09-01 18:04

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript', '0002_auto_20200902_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkmanuscriptmodel',
            name='check_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='check time'),
        ),
        migrations.AlterField(
            model_name='contributiontypemodel',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='add time'),
        ),
        migrations.AlterField(
            model_name='manuscriptmodel',
            name='contribution_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 1, 18, 4, 34, 119989, tzinfo=utc), verbose_name='delivery time'),
        ),
        migrations.AlterField(
            model_name='subjectmodel',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='add time'),
        ),
        migrations.AlterField(
            model_name='trademodel',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='add time'),
        ),
    ]
