# Generated by Django 3.1 on 2020-09-01 18:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript', '0003_auto_20200902_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscriptmodel',
            name='contribution_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='delivery time'),
        ),
    ]
