# Generated by Django 3.1 on 2020-09-08 03:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript', '0004_auto_20200902_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkmanuscriptmodel',
            name='check_contact_way',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='contact way'),
        ),
        migrations.AlterField(
            model_name='checkmanuscriptmodel',
            name='check_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='check name'),
        ),
        migrations.AlterField(
            model_name='checkmanuscriptmodel',
            name='check_status',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='check status'),
        ),
        migrations.AlterField(
            model_name='checkmanuscriptmodel',
            name='check_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='check time'),
        ),
        migrations.AlterField(
            model_name='checkmanuscriptmodel',
            name='duplicate_checking_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='duplicate checking rate'),
        ),
        migrations.AlterField(
            model_name='checkmanuscriptmodel',
            name='is_contribution',
            field=models.BooleanField(blank=True, null=True, verbose_name='contribution'),
        ),
        migrations.AlterField(
            model_name='checkmanuscriptmodel',
            name='is_subject',
            field=models.BooleanField(blank=True, null=True, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='checkmanuscriptmodel',
            name='is_trade',
            field=models.BooleanField(blank=True, null=True, verbose_name='trade'),
        ),
        migrations.AlterField(
            model_name='checkmanuscriptmodel',
            name='multiple_contributions_to_one_manuscript',
            field=models.BooleanField(blank=True, null=True, verbose_name='multiple contributions to one manuscript'),
        ),
    ]
