# Generated by Django 3.1 on 2020-08-21 03:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authtoken', '0002_auto_20160226_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('username', models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='用户账号')),
                ('real_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='真实姓名')),
                ('contact_way', models.CharField(blank=True, max_length=64, null=True, verbose_name='联系方式')),
                ('adress', models.CharField(blank=True, max_length=128, null=True, verbose_name='家庭地址')),
                ('postal_code', models.CharField(blank=True, max_length=12, null=True, verbose_name='邮编')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('sex', models.BooleanField(blank=True, null=True, verbose_name='性别')),
                ('education', models.CharField(blank=True, max_length=64, null=True, verbose_name='学历')),
                ('country', models.CharField(blank=True, max_length=128, null=True, verbose_name='国家')),
                ('province', models.CharField(blank=True, max_length=128, null=True, verbose_name='省份')),
                ('city', models.CharField(blank=True, max_length=128, null=True, verbose_name='城市')),
                ('work_unit', models.CharField(blank=True, max_length=256, null=True, verbose_name='工作单位')),
                ('resume', models.TextField(blank=True, null=True, verbose_name='个人简介')),
            ],
            options={
                'verbose_name': '用户信息表',
                'verbose_name_plural': '用户信息表',
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.token')),
                ('outTime', models.DateTimeField(default=datetime.datetime(2020, 8, 21, 4, 10, 40, 38011))),
            ],
            bases=('authtoken.token',),
        ),
    ]
