# Generated by Django 3.1 on 2020-08-22 03:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinformation',
            options={'permissions': (('vip_user', 'Can vip user'),), 'verbose_name': '用户信息表', 'verbose_name_plural': '用户信息表'},
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='outTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 22, 3, 57, 22, 942704)),
        ),
    ]
