# Generated by Django 3.1 on 2020-08-28 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200823_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='outTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 28, 20, 7, 56, 583803)),
        ),
    ]
