# Generated by Django 3.1 on 2020-09-01 02:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200828_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='outTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 1, 10, 44, 9, 275374)),
        ),
    ]
