# Generated by Django 3.1 on 2020-09-01 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200902_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='outTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 2, 2, 34, 34, 108990)),
        ),
    ]
