# Generated by Django 3.1 on 2020-09-11 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20200908_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='outTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 11, 23, 15, 34, 606374)),
        ),
    ]
